apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      name: http
    - port: 9090
      name: metrics
  selector:
    app: wordpress
